# site settings
title: JessGiehl
subtitle: Fullstack Webdev Student
email: jwgiehl@student.fullsail.edu
description: A portfolio of works by Jessica Giehl.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jessgiehl.github.io/wd6portfolio/" # the base hostname & protocol for your site
city: Orlando
state: FL

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 1

# social settings
github_url: https://github.com/JessGiehl

# build settings
markdown: kramdown

sass:
  style: compressed
